<?php

/**
 * @file
 * Contains form_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function form_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the form_example module.
    case 'help.page.form_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('An example of using the D8 Form API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function form_example_theme() {
  $theme = [];

  return $theme;
}
